###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  clamav:
    image: ${DOCKER_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
    networks:
      default:
        aliases:
          - clamav.local

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - clamav
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=clamav.local:3310
      - WAIT_FOR_TIMEOUT=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - clamav
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # Wait until the tested container is started
      - WAIT_FOR_TCP=clamav.local:3310
      - WAIT_FOR_TIMEOUT=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  test_project_dir:
